# Generated by Django 4.0.3 on 2022-04-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_follows_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follows',
            options={'verbose_name_plural': 'Follows'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name_plural': 'Likes'},
        ),
    ]
